export const GET_API_SERVICE_URL = {
  LOGIN: '/dfrapi/login/signIn',
  GET_DATA: 'api/get/data/',
  GET_DIAGONSIS: 'api/common/getDiagnosisCodeDetails',
  GET_INSTITUTION_NAME_DETAILS: 'api/common/getProviderDetailsByCatg',
  GET_MEMBER_CLIAMS_TEST: 'api/reimbursement/getClaimDetails',
  GET_MEMBER_CLIAMS: 'api/reimbursement/getMyClaimDetailsForMobile',
  GET_MEMBER_CLIAMS_DETAILS: 'api/pec/getClaimDetailsById',
  SAVE_REFERAL_CONTACT: 'api/common/saveReferralData',
  GENERATE_OTP: 'generateOtp',
  VALIDATE_OTP: 'validateOtp',
  SIGNUP: 'api/user/signUp',
  FORGOT_PASSWORD: 'api/login/forgotpassword',
  CHANGE_PASSWORD: 'api/login/changePassword',
  SIGNIN: 'api/user/getUserDetails',
  GUEST_USER_SIGNUP: 'api/login/signIn',
  MEMBER_PROFILE: 'api/dashboard/getMemberProfile',
  MEMBER_PROFILE_DATA: 'api/dashboard/getMemberProfileData',
  SAVE_NEW_CLAIM: 'api/reimbursement/saveClaimDetails',
  UDS_DEFN_DATA: 'api/common/getUdsDefnList',
  SCANDOCUMENT: 'virus/api/scan/uploadFileForScan',
  GET_POLICY_MEMBER_DATA: 'api/core/policy/getPolicyMemberList',
  GET_POLICY_DATA: 'api/core/policy/getPolicyList',
  GET_POLICY_BENEBITS_DATA: 'api/core/policy/getPolicyBenefits',
  GET_POLICY_SUB_BENEBITS_DATA: 'api/core/policy/getPolicySubBenefits',
};
export const GET_WF_EVENT_ID = {
  GET_MY_POLICIES: 'WF_POLICY_LIST',
  GET_POLICY_MEMBER: 'WF_POLICY_MEMBERS',
  GET_MEMBER_BENEGITS: 'WF_POLICY_BENEFITS',
  GET_MEMBER_SUB_BENEGITS: 'WF_POLICY_SUB_BENEFITS',
};
